version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: cimg/mysql:8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update

